### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by oasisfreak** [NVlabs/CSG#1]
Hello Mr. Chen!

thanks for the great work and repository!
Currently, I'm trying to reproduce your numbers stated in the paper. Using your provided code and checkpoints, I cannot achieve the same results.
In my case, I get an mIoU on Cityscapes if 36,141% on the ResNet50 checkpoint.
Does the provided checkpoint differ from the one used for generating the paper results?

Thanks.

**Comment by chenwydj** [comment]
Hi @oasisfreak,

Thank you for your interest in our work!

Thanks for the reminder! The mIoU from this checkpoint is 35.9% evaluated on our side, which is slightly better than we reported. We will update our arxiv soon.
