### ISSUE TITLE
Question about the segmentation model on the paper.

### ISSUE THREAD

**Issue by Genie-Kim** [NVlabs/CSG#3]
Hi, Thanks for your great work!

I have a question about the segmentation model you used in your paper.
The paper on the segmentation model you referred to is as follows. https://arxiv.org/pdf/1706.05587.pdf
As far as I know, this paper is about Deeplabv3.
However, in the paper, it is marked as Deeplabv2.
Can you tell me what is the difference between the segmentation model you used and deeplabv3?

Thank you for reading.

**Comment by chenwydj** [comment]
Hi @Genie-Kim !

Thanks for your interest in our work!

I double-checked and I think it was a typo. We did use DeeplabV3. I will update the arxiv soon.
