### ISSUE TITLE
Question about the kde diagram.

### ISSUE THREAD

**Issue by Genie-Kim** [NVlabs/CSG#4]
Hi, thanks for your great work and for releasing the code.

I want to draw a Gaussian kernel density estimation diagram like figure 1, can you please release the code or give me some advice on how you plotted it?

Thanks for reading.

**Comment by chenwydj** [comment]
Hi @Genie-Kim.

Thanks for your interest in our work and sorry for the late reply!

Here is an example code for the visualization:
```python
from scipy import stats
kernel = stats.gaussian_kde(feature)
frac = 0.3
X, Y = np.mgrid[-1-frac:1+frac:int(100*(1+frac))*1j, -1-frac:1+frac:int(100*(1+frac))*1j]
positions = np.vstack([X.ravel(), Y.ravel()])
Z = np.reshape(kernel(positions).T, X.shape)

fig, ax = plt.subplots()

plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

sc = ax.imshow(np.rot90(Z), cmap=plt.cm.gist_earth_r, extent=[-1-frac, 1+frac, -1-frac, 1+frac])
cbar = plt.colorbar(sc)
cbar.ax.tick_params(labelsize=12)
ax.set_xlim([-1-frac, 1+frac])
ax.set_ylim([-1-frac, 1+frac])
plt.show()
```

**Comment by Genie-Kim** [comment]
Hi @chenwydj!
Thank you so much for sharing additional code for better understanding.
