### ISSUE TITLE
E_s: hyperspherical energy of features

### ISSUE THREAD

**Issue by innovator-arjun** [NVlabs/CSG#5]
Hi Team,
Thank you for the great work and releasing the code. 

We are wondering about the Es: hyperspherical energy of features part in the paper, however in the code base we couldn't find it.

It would be great, if you can guide us or have the implementation part of it to get the E_s part , similar to Table 1 (https://arxiv.org/pdf/2104.02290.pdf)

**Comment by chenwydj** [comment]
Hi @innovator-arjun,

Thanks for your interest in our work!

We use the code here for calculating the E_s: https://github.com/wy1iu/MHE/blob/master/code/architecture.py#L58

Hope that helps!
